### ISSUE TITLE
First login on new browser gives "wrong password" message

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#23]
When trying to log in for the first time in a new browser (or after clearing cache / offline data), the web app rejects the user's password, claiming "wrong password".
After the local PouchDB replication is downloaded and the user tries again, he can successfully log in with the same password that was rejected before.

Adapt the `userManager.login()` function - if local authentication fails, check remote authentication before rejecting the login attempt.

**Comment by fschoell** [comment]
So the reason for the first login failing is that there's no local PouchDB replication available at that time for the userManager? (I tried to look into it, but somehow I can't reproduce this issue as firefox doesn't seem to delete the database even with clear cache / offline data)

If this is the case I don't think we should use the remote authentication in the userManager, because if the replication fails for some reason, then the user is logged in but has no local database available to work with. We could block the `appDB.login()` function until the replication process is done or maybe separate the remote login from the replication (try remote login -> if successful try replication -> if successful try local authentication).

**Comment by sebastian-leidig** [comment]
[ sorry @ojauch , can only assign one person :-( ]

**Comment by ojauch** [comment]
I changed the behavior of the login workflow so that PouchDB syncs one time with the remote db, then waits until the user is successfully loged in and then starts to sync live with the remote db.

**Comment by fschoell** [comment]
Took a short look at it and it looks good. I don't have a lot of time this weekend due to a seminar unfortunately, but I added some gui functionality (the login button is disabled while logging in as it could take a little bit longer if the db has to be synced). 

If you want you can open a pull request for testing.

**Comment by sebastian-leidig** [comment]
Looks great, so far!

The first login takes pretty long, however. 
I would rename the disabled login button to something more explaining like
> Downloading initial database
("Logging in ..." is helpful but doesn't explain the long wait)

**Comment by sebastian-leidig** [comment]
Also, as the database grows I expect it will take even longer to download the initial data before the user can log in.

Maybe we should "split" the database into two "independent" CouchDB databases `db.users` (only containing the user accounts) and `db.data` (with the other data). Then the initial download will always be small.

I didn't test whether that makes a performance difference yet ...

**Comment by fschoell** [comment]
> ("Logging in ..." is helpful but doesn't explain the long wait)

I agree with you there, the intention of the disabled button only was to prevent the user thinking that "nothing is happening". I propose we open a new issue for that, so we can discuss the best way to do this (I like the idea of splitting up the database) without delaying this issue.
