### ISSUE TITLE
Initial setup/installation involves too many commands and takes too much time

### ISSUE THREAD

**Issue by sanindya-iiitd** [NGO-DB/helgo_db#51]
Installing the project for the first time involves many commands (for example, those who don't have npm already installed or have had trouble previously) and takes a lot of time esp. the `npm install` command.

Can we create a script that performs the installation automatically while performing checks if any of the required software is already present?
At the same time can we also speed up the final `npm install` command?

There are also some warnings such as:
`npm WARN prefer global jshint@2.8.0 should be installed with -g`
Can we do something about it?

**Comment by fschoell** [comment]
From my experience there are huge differences between the nodejs and npm versions and that results in a very unreliable behavior of the installation process and package dependencies (I installed nodejs on a freshly installed Ubuntu 14.04 recently and npm was just broken by default for example). The warnings are mostly due to those version changes as well and depend on the dependency handling of the installed packages (which means we can't really do something about them, as that's the responsibility of the package maintainer).

Creating an installation script which handles any previously installed software would be very complex and probably still not working in many cases. I agree that the initial setup is not particularly easy or fast, but I don't see an easy way to do anything about that. On the bright side, as soon as everything is set up adding packages is pretty fast and easy. ;)

**Comment by sanindya-iiitd** [comment]
Thank you for this information.
