### ISSUE TITLE
Alternative (OO) technologies for Javascript?

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#54]
In the long run it might be better to an object oriented programming language like Java. This needs to be carefully evaluated:

Advantages/Disadvantages of
- web/browser-based application (or a stand-alone desktop application)
- frameworks/languages

# "Web App" vs. "Desktop App"

## Pro "Web App"
- Minimale Hürden zur Benutzung (kein Download/Installation für Trial / sporadische Nutzer / ...)
- Einfache Updates & Wartung (direkt auf Server)
- Basis-Funktionen durch Browser gegeben (z.B. Drucken, Resizing, ...)
- Plattformunabhängig (Mac/Linux/Mobile?)
- ...

## Pro "Desktop App"
- Daten allein von der Anwendung verwaltet (nicht im Browser-Cache)
  - Cache -> kann vom Nutzer "ausversehen" gelöscht werden
  - Cache -> Speichergrenzen des Browsers
- Unabhängig von Web-Standards/Javascript/...
- ...

#  Framework
Comparison Angular / GWT:
- http://www.nordeck.net/techblog/-/blogs/gwt-vs-angularjs
- https://groups.google.com/forum/#!topic/angular/9P4RD3IbQwk
- https://dzone.com/articles/java-origins-angular-js

## TypeScript with [AngularJS 2](https://angular.io/features.html) Advantages
:heavy_plus_sign: simple layer of abstraction (only MVC rather than modelling web-pages as abstract objects)
:heavy_plus_sign: supposedly faster/simpler to develop (AngularJS was invented by frustrated GWT developers)
:heavy_plus_sign: trending and has a large ecosystem
:heavy_minus_sign: JavaScript libraries need a TypeScript definition file
- ...
- (easy to reuse/adapt existing code)

## Java + GWT
:heavy_plus_sign: we have more experience developing in Java
:heavy_plus_sign: strongly object oriented
:heavy_minus_sign: dealing with multiple languages (Java and Javascript, as we'll need to deal with some Javascript sooner or later)
:heavy_minus_sign: long compiling times?
:heavy_minus_sign: complicated to include 3rd party libraries? (not 100 percent sure what he means with this, but I assume he relates to 3rd party JavaScript libraries)
:heavy_minus_sign: not working well with a modular structure?
- ...

## Other
- Java (-> Desktop App)
- AngularJS using [Github Electron](http://electron.atom.io/) as Desktop App

**Comment by sebastian-leidig** [comment]
Starting to collect some links here:
- [AngularJS 2 with TypeScript](https://www.youtube.com/watch?v=yy4c0hzNXKw)
  - [AngularJS 2](https://angular.io/features.html)

**Comment by fschoell** [comment]
I like the idea of using TypeScript, it's object-oriented and uses data types. And from my understanding it would be possible to switch gradually to TypeScript rather than having to rewrite everything at once (we could already use TypeScript for AngularJS 1.x and use grunt to compile the TypeScript files to JavaScript, which then can be included as before). This could be a very elegant solution to switch to a better programming language and AngularJS 2 in the future and I think it's worth to take a deeper look into this.

**Comment by fschoell** [comment]
I would like to raise a discussion about web/browser-based apps vs desktop applications, after I researched a bit about the cache handling of firefox and chrome (you can find some information on firefox [here](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria) and about chrome [here](https://developer.chrome.com/apps/offline_storage)). 

First, caching the application/database should be no problem in general, as the browsers mostly have a large quota limit for the cache (like 20% of the free hdd storage). However, there are a couple of possible issues with using the browsers cache to store the database:

- Firefox does offer persistent storage for an IndexedDB, but Chrome does not (see the link above). As of now, persistent storage in Chrome is only available for the file system API. 
- The quota limit for the temporary cache is configurable by the user, we shouldn't rely on the default settings. If a user decides that 200 MB is enough for the cache then we could run into problems really fast. 
- Even the persistent storage will be deleted if the user chooses to clean the cache. 

Now, this won't be an issue most of the times. However, it *can* become a real nightmare if a database would be somehow deleted by either the user or the browser - this could mean that the users work is lost if he hasn't synchronized the database for a certain time. As for now we can instruct the social workers on how to setup their browsers and sensitize them to *never* clean the cache - but in my opinion we should not rely on the users technical understanding in the future.

**Comment by fschoell** [comment]
If we decide to stay with AngularJS we could take a look into building a native desktop application with [Github Electron](http://electron.atom.io/) and mobile applications - if needed - with PhoneGap or Cordova. All of them are supported by PouchDB ([source](http://pouchdb.com/faq.html#native_support))

**Comment by sebastian-leidig** [comment]
Some sources comparing Angular and GWT:
http://www.nordeck.net/techblog/-/blogs/gwt-vs-angularjs
https://groups.google.com/forum/#!topic/angular/9P4RD3IbQwk

**Comment by sebastian-leidig** [comment]
"Hello World" Tutorials:
- Angular2/TypeScript: https://angular.io/docs/ts/latest/quickstart.html
- Java GWT: ?

**Comment by fschoell** [comment]
A possible disadvantage of AngularJS 2 with TypeScript I found is that you need a TypeScript definition file for every JavaScript library you're using. There's a project called [DefinetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) which creates those files for the most popular libraries so that shouldn't become a larger problem in general. However, it could get us into some trouble with smaller or more unpopular libraries we might want to use.

I found some disadvantages of GWT in the comparison in the Google forum thread which I haven't been aware of before (cannot confirm if they affect the recent GWT versions as well, but we should look into those). Those are long compiling times, it's complicated to include 3rd party libraries (not 100 percent sure what he means with this, but I assume he relates to 3rd party JavaScript libraries) and GWT seems to be not working well with a modular structure.

**Comment by sebastian-leidig** [comment]
"Hello World" Tutorials:
- Angular2/TypeScript: https://angular.io/docs/ts/latest/quickstart.html , https://angular.io/docs/ts/latest/tutorial/
- Java GWT: ?

**Comment by sebastian-leidig** [comment]
**Entscheidung für Typescript/Angular2**
